### PR TITLE
Enable to search groups by name

### PR DESCRIPTION
**Pull request by yurir**
According to rocket api there is an option to search room by name and it's important feature. Please allow pull request

### CODE REVIEW

**Comment by yurir** [comment]
@qeesung 
Hi, Please let me know if the pull request is ok. I'd like to have a possibility to search room by name. I checked it locally and the change works for me.

**Comment by qeesung** [comment]
@yurir Would you like to add some test cases for this api ?

**Comment by yurir** [comment]
I will. Could you please guide me how to run tests locally? Or just give me
name of related test framework.

On Feb 14, 2018 17:11, "秦世成" <notifications@github.com> wrote:

@yurir <https://github.com/yurir> Would you like to add some test cases for
this api ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/qeesung/rocketchat-node/pull/74#issuecomment-365636918>,
or mute the thread

**Comment by yurir** [comment]
Pushed a test.  Not familiar with this framework. Waiting for result.

**Comment by yurir** [comment]
@qeesung Could you please have a look to the test? The variable is defined. Why does it fail?

**Comment by yurir** [comment]
@qeesung any chance you can help with failing test?

**Comment by MatthiasKainer** [comment]
@yurir the problem is, as said by the test, that the variable does not exist. Codacity says the same. 

You will have to create the variable and persist the group name in the before method that created a group. Those are integration tests, so they work against a running instance of rocket-chat and need your group to exist.

**Comment by MatthiasKainer** [comment]
btw, you can create an integration test env if you have docker on your machine with `./test/setup-testenv.sh` - afterwards you can execute the test with `npm test` or debug in a ide of your choice and don't have to wait for travis.

**Comment by yurir** [comment]
@MatthiasKainer thanks for the direction.

I have rocket running locally in docker and tests are failing even without my new test. I will try again later this week and will post here errors I get.

**Comment by yurir** [comment]
@MatthiasKainer  thanks for the help. Your tips worked and i could run the tests locally. I fixed the tests!

@qeesung Could you approve my pull request now?

**Comment by qeesung** [comment]
lgtm

**Pull request merged**
