### PR TITLE
fixed inconsistent callbacking to allow promise-support

### PR DESCRIPTION
**Pull request by MatthiasKainer**
the new client had a callback function not following (err, body) - pattern. With this fixed you should be able to promisify the whole thing more easily

### CODE REVIEW

**Comment by qeesung** [comment]
I have a question, If then client should connect to the rocketchat server when the client is created?

**Comment by MatthiasKainer** [comment]
With the current solution you can avoid that by not passing username/password. If you think it makes more sense we could think about not connecting as well - for the tests it was simply handy this way :)

**Comment by MatthiasKainer** [comment]
I just remembered I did this for consistency with the realtime api as  well - here you need an open connection for subscriptions

**Comment by qeesung** [comment]
nice job.

**Pull request merged**
