### PR TITLE
make tests working for IM

### PR DESCRIPTION
**Pull request by MatthiasKainer**
implementing #58

### CODE REVIEW

**Comment by MatthiasKainer** [comment]
@qeesung webhooks seem broken - no travis nor codacy :dizzy_face: 
Is this a local issue, or is anything working on your screen?

**Comment by qeesung** [comment]
@MatthiasKainer Good job!  everything is work on my screen. Is it not work in my repo or in your forked repo ?

**Comment by MatthiasKainer** [comment]
Sry, there's a lot going on under the water atm and didn't found much time to look into it 

Works now, seemingly was a problem with my browser. Maybe one of greasemonkeyscripts ran amok ^^

Is this mr good enough for now, and we'll add a task for the other tests, or should we implement them all in one mr?

**Comment by qeesung** [comment]
Maybe we can implement the rest of tests in this pr. I can too busy to work on this project rencently :cry:

**Comment by MatthiasKainer** [comment]
np. we already came a long way in a very fast pace - there's plenty of time to catch our breath :)

**Comment by qeesung** [comment]
I seems that I can not make contribute to you im-tests branch, I will merge this mr, and reopen a new branch to implement the rest test case

**Pull request merged**
