### PR TITLE
Users add remove info

### PR DESCRIPTION
**Pull request by MatthiasKainer**
@qeesung implemented user methods. had some problems with creating a user - the call never returns, neither webapi nor websocket. implemented a workaround where I query the users after 500ms. Ugly solution for now - I'll open an issue with rocketchat and link it

### CODE REVIEW

**Comment by MatthiasKainer** [comment]
Bug openend here https://github.com/RocketChat/Rocket.Chat/issues/6733

**Comment by qeesung** [comment]
Yes! I debug the create user interface this night, and catch the exception 

```json
{
  "success": false,
  "error": "Adding user is not allowed [error-action-not-allowed]",
  "errorType": "error-action-not-allowed"
}
```

**Comment by MatthiasKainer** [comment]
Haven't even received that message - timed out. 

User is created however. The current implementation works around the issue by simply not waiting for the callback,

**Comment by qeesung** [comment]
If you run create user unit test with `mocha` , it will be timeout.

So then I try to create user with `curl`, then  received  the "error-action-not-allowed" message

**Comment by MatthiasKainer** [comment]
works on travis. guess we'll have to fix our local config.
@qeesung for me this pr is final and ready to be merged. pls review

**Comment by qeesung** [comment]
Okay , the rocketchat I deploy with docker-compose also meet the create user failed exception.

**Pull request merged**
