### PR TITLE
change channels to ES6 syntax

### PR DESCRIPTION
**Pull request by qeesung**

### CODE REVIEW

**Comment by qeesung** [comment]
In this pull request what I added:

1. Support all channel interfaces
2. Make the `RestClient` request method support return a Promise(use `bluebird` module)
3. Use `eslint` for style check, and create `.eslint.yml` and `.eslintignore` file
4. Add `channel` test cases.

**Comment by qeesung** [comment]
I found that `setType` interface always throws a expection that said "RoomId can not found"

**Comment by MatthiasKainer** [comment]
wow, you had one busy weekend :smiley:

**Comment by qeesung** [comment]
😆 Only Saturday and Sunday are my free coding time, I will merge these two pr's

**Pull request merged**
